# Generated by Django 3.2.6 on 2024-06-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_notes_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medium',
            field=models.CharField(choices=[('Marathi', 'Marathi'), ('SemiEng', 'SemiEng'), ('CBSE', 'CBSE'), ('Foundation', 'Foundation')], default='Marathi', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=10),
        ),
    ]
